---
- name: "Postman"
  tags: postman
  block:
  - name: "Postman - Check installation"
    stat: path=/opt/Postman
    register: postman
  - name: "Postman - Download"
    get_url:
      url: https://dl.pstmn.io/download/latest/linux64
      dest: /opt/Postman-linux-x86_64.tar.gz
    when: (not postman.stat.exists)
  - name: "Postman - Install"
    unarchive:
      src: /opt/Postman-linux-x86_64.tar.gz
      dest: /opt
    when: (not postman.stat.exists)
  - name: "Postman - Change Owner"
    file:
      path: /opt/Postman
      state: directory
      recurse: yes
      owner: "{{user}}"
      group: "{{group}}"
    when: (not postman.stat.exists)
  - name: "Postman - Create Menu Icon"
    copy:
      src: assets/postman.desktop
      dest: /usr/share/applications/postman.desktop
    when: (not postman.stat.exists)
  - name: "Postman - Clean"
    file:
      path: /opt/Postman-linux-x86_64.tar.gz
      state: absent
    when: (not postman.stat.exists)
